import { Theme } from './types'

export const PREBUILT_THEMES: Record<string, Theme> = {
  darkWorship: {
    id: 'dark-worship',
    name: 'Dark Worship',
    fontFamily: '"Merriweather", serif',
    fontSize: 48,
    fontWeight: '600',
    textAlignment: 'center',
    backgroundColor: '#0a0e27',
    textColor: '#f5f5f5',
    accentColor: '#6366f1',
    backgroundStyle: 'solid',
    transitionType: 'fade',
    transitionDuration: 600,
    isPrebuilt: true,
  },
  lightMinimal: {
    id: 'light-minimal',
    name: 'Light Minimal',
    fontFamily: '"Inter", sans-serif',
    fontSize: 44,
    fontWeight: 'normal',
    textAlignment: 'center',
    backgroundColor: '#ffffff',
    textColor: '#1a1a1a',
    accentColor: '#2563eb',
    backgroundStyle: 'solid',
    transitionType: 'fade',
    transitionDuration: 500,
    isPrebuilt: true,
  },
  scriptureFocus: {
    id: 'scripture-focus',
    name: 'Scripture Focus',
    fontFamily: '"Georgia", serif',
    fontSize: 52,
    fontWeight: '700',
    textAlignment: 'center',
    backgroundColor: '#1a1a2e',
    textColor: '#ffd700',
    accentColor: '#ffd700',
    backgroundStyle: 'solid',
    transitionType: 'slide',
    transitionDuration: 800,
    isPrebuilt: true,
  },
  youthMode: {
    id: 'youth-mode',
    name: 'Youth Mode',
    fontFamily: '"Poppins", sans-serif',
    fontSize: 42,
    fontWeight: '600',
    textAlignment: 'center',
    backgroundColor: '#1a1a2e',
    textColor: '#00d4ff',
    accentColor: '#ff006e',
    backgroundStyle: 'solid',
    transitionType: 'zoom',
    transitionDuration: 700,
    isPrebuilt: true,
  },
}

export const DEFAULT_THEME = PREBUILT_THEMES.darkWorship
